name: NEWStream

settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: 'YES'

options:
  minimumXcodeGenVersion: 2.32
  bundleIdPrefix: com.newstream
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "15.0"

packages:
  NEWStreamApp:
    path: Modules/NEWStreamApp

targets:
  NEWStream:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    dependencies:
      - package: NEWStreamApp

    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1
        SWIFT_VERSION: 5.7
        INFOPLIST_FILE: "Resources/Info.plist"

    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: NEWStream
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait 

    sources:
      - path: Code
      - path: Resources

schemes:
  NEWStream:
    build:
      targets:
        NEWStream: all
      parallelizeBuild: true
      buildImplicitDependencies: true